# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KBDashBoard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KBDashBoard
  pod 'ZohoDeskPortalKB', :path => "/Users/rajesh-tt221/Documents/ASAP ios with platform"
  pod 'ZohoDeskPortalAPIKit', :path => "/Users/rajesh-tt221/Documents/ASAP ios with platform"
  pod 'ZohoDeskPortalConfiguration', :path => "/Users/rajesh-tt221/Documents/ASAP ios with platform"
  pod 'ZohoDeskPlatformDataBridge', :path => "/Users/rajesh-tt221/Documents/desk-platform-sdk-ios"
  pod 'ZohoDeskPlatformUIKit', :path => "/Users/rajesh-tt221/Documents/desk-platform-sdk-ios"

end
